version: 1
language: go
# Coverage policy configuration
policy:
  default:
    min: 60
  domains:
    - name: cmd
      match:
        - ./cmd/...
      min: 30  # CLI entry points, lower coverage expected
    - name: application
      match:
        - ./pkg/application/...
      min: 75  # Core services, target 75%+
    - name: domain
      match:
        - ./pkg/domain/...
      min: 73  # Domain logic, target 73%+
    - name: infrastructure
      match:
        - ./internal/infrastructure/...
      min: 60  # Adapters, 60% baseline
