version: 1
language: go
# Coverage policy configuration
policy:
  default:
    min: 60
  domains:
    - name: cmd
      match:
        - ./cmd/...
      min: 80  # Plugin binaries with httptest coverage
    - name: application
      match:
        - ./pkg/application/...
      min: 80  # Core services
    - name: domain
      match:
        - ./pkg/domain/...
      min: 80  # Domain logic
    - name: infrastructure
      match:
        - ./internal/infrastructure/...
      min: 80  # Adapters and CLI
