version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - gocritic
    - errcheck
    - staticcheck
    - unused
  settings:
    gocritic:
      disabled-checks:
        - deprecatedComment  # Fixing format triggers 195 SA1019 usages; defer to migration PR
