# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: roady
    main: ./cmd/roady/main.go
    binary: roady
    ldflags:
      - -s -w
      - -X github.com/felixgeelhaar/roady/internal/infrastructure/cli.Version={{.Version}}
      - -X github.com/felixgeelhaar/roady/internal/infrastructure/cli.Commit={{.Commit}}
      - -X github.com/felixgeelhaar/roady/internal/infrastructure/cli.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: roady-plugin-linear
    main: ./cmd/roady-plugin-linear/main.go
    binary: roady-plugin-linear
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: roady-plugin-jira
    main: ./cmd/roady-plugin-jira/main.go
    binary: roady-plugin-jira
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with what people expect.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: roady
    repository:
      owner: felixgeelhaar
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://felixgeelhaar.github.io/roady/"
    description: "A planning-first system of record for software work."
    license: "MIT"
    install: |
      bin.install "roady"
      bin.install "roady-plugin-linear"
      bin.install "roady-plugin-jira"
