// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pkg/domain/plugin/proto/syncer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InitRequest contains configuration for the syncer.
type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// InitResponse indicates initialization success.
type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SyncRequest contains the plan and state to sync.
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	State         *ExecutionState        `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRequest) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *SyncRequest) GetState() *ExecutionState {
	if x != nil {
		return x.State
	}
	return nil
}

// SyncResponse contains the sync result.
type SyncResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	StatusUpdates map[string]string       `protobuf:"bytes,1,rep,name=status_updates,json=statusUpdates,proto3" json:"status_updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LinkUpdates   map[string]*ExternalRef `protobuf:"bytes,2,rep,name=link_updates,json=linkUpdates,proto3" json:"link_updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Errors        []string                `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP(), []int{3}
}

func (x *SyncResponse) GetStatusUpdates() map[string]string {
	if x != nil {
		return x.StatusUpdates
	}
	return nil
}

func (x *SyncResponse) GetLinkUpdates() map[string]*ExternalRef {
	if x != nil {
		return x.LinkUpdates
	}
	return nil
}

func (x *SyncResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// PushRequest contains a task status change to push.
type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP(), []int{4}
}

func (x *PushRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PushRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// PushResponse indicates push success.
type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP(), []int{5}
}

func (x *PushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SubscribeRequest contains subscription parameters.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []string               `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

// Event represents an event from the external system.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP(), []int{7}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Event) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Plan represents a Roady plan.
type Plan struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SpecId         string                 `protobuf:"bytes,2,opt,name=spec_id,json=specId,proto3" json:"spec_id,omitempty"`
	Tasks          []*Task                `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	ApprovalStatus string                 `protobuf:"bytes,4,opt,name=approval_status,json=approvalStatus,proto3" json:"approval_status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP(), []int{8}
}

func (x *Plan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plan) GetSpecId() string {
	if x != nil {
		return x.SpecId
	}
	return ""
}

func (x *Plan) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Plan) GetApprovalStatus() string {
	if x != nil {
		return x.ApprovalStatus
	}
	return ""
}

func (x *Plan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Plan) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Task represents a task in a plan.
type Task struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Phase         string                  `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	Outcome       string                  `protobuf:"bytes,5,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Dependencies  []string                `protobuf:"bytes,6,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	ExternalRefs  map[string]*ExternalRef `protobuf:"bytes,7,rep,name=external_refs,json=externalRefs,proto3" json:"external_refs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP(), []int{9}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Task) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *Task) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Task) GetExternalRefs() map[string]*ExternalRef {
	if x != nil {
		return x.ExternalRefs
	}
	return nil
}

// ExecutionState represents the execution state of tasks.
type ExecutionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskStates    map[string]*TaskResult `protobuf:"bytes,1,rep,name=task_states,json=taskStates,proto3" json:"task_states,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionState) Reset() {
	*x = ExecutionState{}
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionState) ProtoMessage() {}

func (x *ExecutionState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionState.ProtoReflect.Descriptor instead.
func (*ExecutionState) Descriptor() ([]byte, []int) {
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP(), []int{10}
}

func (x *ExecutionState) GetTaskStates() map[string]*TaskResult {
	if x != nil {
		return x.TaskStates
	}
	return nil
}

// TaskResult represents the result/state of a task.
type TaskResult struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Owner         string                  `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	StartedAt     *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	ExternalRefs  map[string]*ExternalRef `protobuf:"bytes,5,rep,name=external_refs,json=externalRefs,proto3" json:"external_refs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP(), []int{11}
}

func (x *TaskResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResult) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TaskResult) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TaskResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TaskResult) GetExternalRefs() map[string]*ExternalRef {
	if x != nil {
		return x.ExternalRefs
	}
	return nil
}

// ExternalRef represents a reference to an external system.
type ExternalRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	LastSyncedAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_synced_at,json=lastSyncedAt,proto3" json:"last_synced_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalRef) Reset() {
	*x = ExternalRef{}
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalRef) ProtoMessage() {}

func (x *ExternalRef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_domain_plugin_proto_syncer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalRef.ProtoReflect.Descriptor instead.
func (*ExternalRef) Descriptor() ([]byte, []int) {
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP(), []int{12}
}

func (x *ExternalRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalRef) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ExternalRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExternalRef) GetLastSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncedAt
	}
	return nil
}

var File_pkg_domain_plugin_proto_syncer_proto protoreflect.FileDescriptor

const file_pkg_domain_plugin_proto_syncer_proto_rawDesc = "" +
	"\n" +
	"$pkg/domain/plugin/proto/syncer.proto\x12\x0froady.plugin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n" +
	"\vInitRequest\x12@\n" +
	"\x06config\x18\x01 \x03(\v2(.roady.plugin.v1.InitRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\fInitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"o\n" +
	"\vSyncRequest\x12)\n" +
	"\x04plan\x18\x01 \x01(\v2\x15.roady.plugin.v1.PlanR\x04plan\x125\n" +
	"\x05state\x18\x02 \x01(\v2\x1f.roady.plugin.v1.ExecutionStateR\x05state\"\xf2\x02\n" +
	"\fSyncResponse\x12W\n" +
	"\x0estatus_updates\x18\x01 \x03(\v20.roady.plugin.v1.SyncResponse.StatusUpdatesEntryR\rstatusUpdates\x12Q\n" +
	"\flink_updates\x18\x02 \x03(\v2..roady.plugin.v1.SyncResponse.LinkUpdatesEntryR\vlinkUpdates\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\x1a@\n" +
	"\x12StatusUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\\\n" +
	"\x10LinkUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.roady.plugin.v1.ExternalRefR\x05value:\x028\x01\">\n" +
	"\vPushRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\">\n" +
	"\fPushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"3\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"\xb1\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12@\n" +
	"\bmetadata\x18\a \x03(\v2$.roady.plugin.v1.Event.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x01\n" +
	"\x04Plan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aspec_id\x18\x02 \x01(\tR\x06specId\x12+\n" +
	"\x05tasks\x18\x03 \x03(\v2\x15.roady.plugin.v1.TaskR\x05tasks\x12'\n" +
	"\x0fapproval_status\x18\x04 \x01(\tR\x0eapprovalStatus\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xcf\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x18\n" +
	"\aoutcome\x18\x05 \x01(\tR\aoutcome\x12\"\n" +
	"\fdependencies\x18\x06 \x03(\tR\fdependencies\x12L\n" +
	"\rexternal_refs\x18\a \x03(\v2'.roady.plugin.v1.Task.ExternalRefsEntryR\fexternalRefs\x1a]\n" +
	"\x11ExternalRefsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.roady.plugin.v1.ExternalRefR\x05value:\x028\x01\"\xbe\x01\n" +
	"\x0eExecutionState\x12P\n" +
	"\vtask_states\x18\x01 \x03(\v2/.roady.plugin.v1.ExecutionState.TaskStatesEntryR\n" +
	"taskStates\x1aZ\n" +
	"\x0fTaskStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.roady.plugin.v1.TaskResultR\x05value:\x028\x01\"\xe7\x02\n" +
	"\n" +
	"TaskResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12R\n" +
	"\rexternal_refs\x18\x05 \x03(\v2-.roady.plugin.v1.TaskResult.ExternalRefsEntryR\fexternalRefs\x1a]\n" +
	"\x11ExternalRefsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.roady.plugin.v1.ExternalRefR\x05value:\x028\x01\"\x91\x01\n" +
	"\vExternalRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12@\n" +
	"\x0elast_synced_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncedAt2\xa1\x02\n" +
	"\x06Syncer\x12C\n" +
	"\x04Init\x12\x1c.roady.plugin.v1.InitRequest\x1a\x1d.roady.plugin.v1.InitResponse\x12C\n" +
	"\x04Sync\x12\x1c.roady.plugin.v1.SyncRequest\x1a\x1d.roady.plugin.v1.SyncResponse\x12C\n" +
	"\x04Push\x12\x1c.roady.plugin.v1.PushRequest\x1a\x1d.roady.plugin.v1.PushResponse\x12H\n" +
	"\tSubscribe\x12!.roady.plugin.v1.SubscribeRequest\x1a\x16.roady.plugin.v1.Event0\x01B8Z6github.com/felixgeelhaar/roady/pkg/domain/plugin/protob\x06proto3"

var (
	file_pkg_domain_plugin_proto_syncer_proto_rawDescOnce sync.Once
	file_pkg_domain_plugin_proto_syncer_proto_rawDescData []byte
)

func file_pkg_domain_plugin_proto_syncer_proto_rawDescGZIP() []byte {
	file_pkg_domain_plugin_proto_syncer_proto_rawDescOnce.Do(func() {
		file_pkg_domain_plugin_proto_syncer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_domain_plugin_proto_syncer_proto_rawDesc), len(file_pkg_domain_plugin_proto_syncer_proto_rawDesc)))
	})
	return file_pkg_domain_plugin_proto_syncer_proto_rawDescData
}

var file_pkg_domain_plugin_proto_syncer_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_domain_plugin_proto_syncer_proto_goTypes = []any{
	(*InitRequest)(nil),           // 0: roady.plugin.v1.InitRequest
	(*InitResponse)(nil),          // 1: roady.plugin.v1.InitResponse
	(*SyncRequest)(nil),           // 2: roady.plugin.v1.SyncRequest
	(*SyncResponse)(nil),          // 3: roady.plugin.v1.SyncResponse
	(*PushRequest)(nil),           // 4: roady.plugin.v1.PushRequest
	(*PushResponse)(nil),          // 5: roady.plugin.v1.PushResponse
	(*SubscribeRequest)(nil),      // 6: roady.plugin.v1.SubscribeRequest
	(*Event)(nil),                 // 7: roady.plugin.v1.Event
	(*Plan)(nil),                  // 8: roady.plugin.v1.Plan
	(*Task)(nil),                  // 9: roady.plugin.v1.Task
	(*ExecutionState)(nil),        // 10: roady.plugin.v1.ExecutionState
	(*TaskResult)(nil),            // 11: roady.plugin.v1.TaskResult
	(*ExternalRef)(nil),           // 12: roady.plugin.v1.ExternalRef
	nil,                           // 13: roady.plugin.v1.InitRequest.ConfigEntry
	nil,                           // 14: roady.plugin.v1.SyncResponse.StatusUpdatesEntry
	nil,                           // 15: roady.plugin.v1.SyncResponse.LinkUpdatesEntry
	nil,                           // 16: roady.plugin.v1.Event.MetadataEntry
	nil,                           // 17: roady.plugin.v1.Task.ExternalRefsEntry
	nil,                           // 18: roady.plugin.v1.ExecutionState.TaskStatesEntry
	nil,                           // 19: roady.plugin.v1.TaskResult.ExternalRefsEntry
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_pkg_domain_plugin_proto_syncer_proto_depIdxs = []int32{
	13, // 0: roady.plugin.v1.InitRequest.config:type_name -> roady.plugin.v1.InitRequest.ConfigEntry
	8,  // 1: roady.plugin.v1.SyncRequest.plan:type_name -> roady.plugin.v1.Plan
	10, // 2: roady.plugin.v1.SyncRequest.state:type_name -> roady.plugin.v1.ExecutionState
	14, // 3: roady.plugin.v1.SyncResponse.status_updates:type_name -> roady.plugin.v1.SyncResponse.StatusUpdatesEntry
	15, // 4: roady.plugin.v1.SyncResponse.link_updates:type_name -> roady.plugin.v1.SyncResponse.LinkUpdatesEntry
	20, // 5: roady.plugin.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	16, // 6: roady.plugin.v1.Event.metadata:type_name -> roady.plugin.v1.Event.MetadataEntry
	9,  // 7: roady.plugin.v1.Plan.tasks:type_name -> roady.plugin.v1.Task
	20, // 8: roady.plugin.v1.Plan.created_at:type_name -> google.protobuf.Timestamp
	20, // 9: roady.plugin.v1.Plan.updated_at:type_name -> google.protobuf.Timestamp
	17, // 10: roady.plugin.v1.Task.external_refs:type_name -> roady.plugin.v1.Task.ExternalRefsEntry
	18, // 11: roady.plugin.v1.ExecutionState.task_states:type_name -> roady.plugin.v1.ExecutionState.TaskStatesEntry
	20, // 12: roady.plugin.v1.TaskResult.started_at:type_name -> google.protobuf.Timestamp
	20, // 13: roady.plugin.v1.TaskResult.completed_at:type_name -> google.protobuf.Timestamp
	19, // 14: roady.plugin.v1.TaskResult.external_refs:type_name -> roady.plugin.v1.TaskResult.ExternalRefsEntry
	20, // 15: roady.plugin.v1.ExternalRef.last_synced_at:type_name -> google.protobuf.Timestamp
	12, // 16: roady.plugin.v1.SyncResponse.LinkUpdatesEntry.value:type_name -> roady.plugin.v1.ExternalRef
	12, // 17: roady.plugin.v1.Task.ExternalRefsEntry.value:type_name -> roady.plugin.v1.ExternalRef
	11, // 18: roady.plugin.v1.ExecutionState.TaskStatesEntry.value:type_name -> roady.plugin.v1.TaskResult
	12, // 19: roady.plugin.v1.TaskResult.ExternalRefsEntry.value:type_name -> roady.plugin.v1.ExternalRef
	0,  // 20: roady.plugin.v1.Syncer.Init:input_type -> roady.plugin.v1.InitRequest
	2,  // 21: roady.plugin.v1.Syncer.Sync:input_type -> roady.plugin.v1.SyncRequest
	4,  // 22: roady.plugin.v1.Syncer.Push:input_type -> roady.plugin.v1.PushRequest
	6,  // 23: roady.plugin.v1.Syncer.Subscribe:input_type -> roady.plugin.v1.SubscribeRequest
	1,  // 24: roady.plugin.v1.Syncer.Init:output_type -> roady.plugin.v1.InitResponse
	3,  // 25: roady.plugin.v1.Syncer.Sync:output_type -> roady.plugin.v1.SyncResponse
	5,  // 26: roady.plugin.v1.Syncer.Push:output_type -> roady.plugin.v1.PushResponse
	7,  // 27: roady.plugin.v1.Syncer.Subscribe:output_type -> roady.plugin.v1.Event
	24, // [24:28] is the sub-list for method output_type
	20, // [20:24] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pkg_domain_plugin_proto_syncer_proto_init() }
func file_pkg_domain_plugin_proto_syncer_proto_init() {
	if File_pkg_domain_plugin_proto_syncer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_domain_plugin_proto_syncer_proto_rawDesc), len(file_pkg_domain_plugin_proto_syncer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_domain_plugin_proto_syncer_proto_goTypes,
		DependencyIndexes: file_pkg_domain_plugin_proto_syncer_proto_depIdxs,
		MessageInfos:      file_pkg_domain_plugin_proto_syncer_proto_msgTypes,
	}.Build()
	File_pkg_domain_plugin_proto_syncer_proto = out.File
	file_pkg_domain_plugin_proto_syncer_proto_goTypes = nil
	file_pkg_domain_plugin_proto_syncer_proto_depIdxs = nil
}
