package ai

import (
	"context"
	"fmt"
	"strings"

	"github.com/felixgeelhaar/roady/pkg/domain/ai"
)

type MockProvider struct {
	Model string
}

func (p *MockProvider) ID() string {
	return "mock:" + p.Model
}

func (p *MockProvider) Complete(ctx context.Context, req ai.CompletionRequest) (*ai.CompletionResponse, error) {
	text := fmt.Sprintf("Mock response for prompt: %s", req.Prompt)
	if strings.Contains(req.Prompt, "JSON") || strings.Contains(req.System, "JSON") {
		text = `[{"id": "task-meta-1", "title": "Mock AI Task", "description": "Generated by mock", "priority": "medium", "estimate": "1h", "feature_id": "core-foundation"}]`
	}

	return &ai.CompletionResponse{
		Text:  text,
		Model: p.Model,
		Usage: ai.TokenUsage{
			InputTokens:  10,
			OutputTokens: 20,
		},
	}, nil
}
