package ai

import (
	"context"
	"fmt"
	"strings"

	"github.com/felixgeelhaar/roady/pkg/domain/ai"
)

type MockProvider struct {
	Model string
}

func (p *MockProvider) ID() string {
	return "mock:" + p.Model
}

func (p *MockProvider) Complete(ctx context.Context, req ai.CompletionRequest) (*ai.CompletionResponse, error) {
	text := fmt.Sprintf("Mock response for prompt: %s", req.Prompt)
	if strings.Contains(req.Prompt, "JSON") || strings.Contains(req.System, "JSON") {
		text = `[{"id": "task-meta-1", "title": "Mock AI Task", "description": "Generated by mock", "priority": "medium", "estimate": "1h", "feature_id": "core-foundation"}]`
	}

	// Honour the streaming contract when the caller opts in: deliver the
	// response in word-sized chunks before returning the assembled text.
	// Providers that only know how to block end up calling OnToken once
	// (or not at all); structured responses like the JSON branch above
	// stream as a single chunk so callers don't see partial JSON.
	if req.OnToken != nil {
		streamMockResponse(ctx, text, req.OnToken)
	}

	return &ai.CompletionResponse{
		Text:  text,
		Model: p.Model,
		Usage: ai.TokenUsage{
			InputTokens:  10,
			OutputTokens: 20,
		},
	}, nil
}

// streamMockResponse emits chunks honouring context cancellation. JSON
// payloads are emitted as a single chunk to avoid handing partial JSON to
// callers that may try to parse it incrementally.
func streamMockResponse(ctx context.Context, text string, onToken func(string)) {
	if strings.HasPrefix(strings.TrimSpace(text), "[") || strings.HasPrefix(strings.TrimSpace(text), "{") {
		onToken(text)
		return
	}
	for _, word := range strings.SplitAfter(text, " ") {
		if word == "" {
			continue
		}
		select {
		case <-ctx.Done():
			return
		default:
		}
		onToken(word)
	}
}
