package application

import "github.com/felixgeelhaar/roady/pkg/domain/spec"

// Template represents a starter project template.
type Template struct {
	Name        string
	Description string
	Spec        func(projectName string) *spec.ProductSpec
}

// BuiltinTemplates returns the available starter templates.
func BuiltinTemplates() []Template {
	return []Template{
		{
			Name:        "minimal",
			Description: "Bare-bones project with a single core feature",
			Spec: func(name string) *spec.ProductSpec {
				return &spec.ProductSpec{
					ID:          name,
					Title:       name,
					Description: "Initial product specification generated by roady.",
					Version:     "0.1.0",
					Features: []spec.Feature{
						{
							ID:          "core-foundation",
							Title:       "Core Foundation",
							Description: "The essential building blocks of the project.",
						},
					},
				}
			},
		},
		{
			Name:        "web-api",
			Description: "REST API service with authentication and data endpoints",
			Spec: func(name string) *spec.ProductSpec {
				return &spec.ProductSpec{
					ID:          name,
					Title:       name,
					Description: "A web API service.",
					Version:     "0.1.0",
					Features: []spec.Feature{
						{
							ID:          "api-endpoints",
							Title:       "API Endpoints",
							Description: "RESTful API endpoints for core resources.",
							Requirements: []spec.Requirement{
								{ID: "req-crud", Title: "CRUD operations for primary resources"},
								{ID: "req-validation", Title: "Request validation and error responses"},
							},
						},
						{
							ID:          "authentication",
							Title:       "Authentication",
							Description: "User authentication and authorization.",
							Requirements: []spec.Requirement{
								{ID: "req-auth", Title: "Token-based authentication"},
								{ID: "req-rbac", Title: "Role-based access control"},
							},
						},
						{
							ID:          "observability",
							Title:       "Observability",
							Description: "Logging, metrics, and health checks.",
							Requirements: []spec.Requirement{
								{ID: "req-health", Title: "Health check endpoint"},
								{ID: "req-logging", Title: "Structured request logging"},
							},
						},
					},
				}
			},
		},
		{
			Name:        "cli-tool",
			Description: "Command-line tool with subcommands and configuration",
			Spec: func(name string) *spec.ProductSpec {
				return &spec.ProductSpec{
					ID:          name,
					Title:       name,
					Description: "A command-line tool.",
					Version:     "0.1.0",
					Features: []spec.Feature{
						{
							ID:          "core-commands",
							Title:       "Core Commands",
							Description: "Primary CLI commands and subcommands.",
							Requirements: []spec.Requirement{
								{ID: "req-commands", Title: "Implement primary subcommands"},
								{ID: "req-help", Title: "Help text and usage documentation"},
							},
						},
						{
							ID:          "configuration",
							Title:       "Configuration",
							Description: "Configuration file support and environment variables.",
							Requirements: []spec.Requirement{
								{ID: "req-config-file", Title: "YAML/JSON config file support"},
								{ID: "req-env-vars", Title: "Environment variable overrides"},
							},
						},
					},
				}
			},
		},
		{
			Name:        "library",
			Description: "Reusable library with public API and documentation",
			Spec: func(name string) *spec.ProductSpec {
				return &spec.ProductSpec{
					ID:          name,
					Title:       name,
					Description: "A reusable library.",
					Version:     "0.1.0",
					Features: []spec.Feature{
						{
							ID:          "public-api",
							Title:       "Public API",
							Description: "The public interface exposed to consumers.",
							Requirements: []spec.Requirement{
								{ID: "req-api-design", Title: "Design clean, idiomatic public API"},
								{ID: "req-docs", Title: "Godoc/JSDoc documentation for all exports"},
							},
						},
						{
							ID:          "testing",
							Title:       "Testing",
							Description: "Comprehensive test suite for the library.",
							Requirements: []spec.Requirement{
								{ID: "req-unit-tests", Title: "Unit tests with high coverage"},
								{ID: "req-examples", Title: "Example tests demonstrating usage"},
							},
						},
					},
				}
			},
		},
	}
}

// FindTemplate returns the template with the given name, or nil.
func FindTemplate(name string) *Template {
	for _, t := range BuiltinTemplates() {
		if t.Name == name {
			return &t
		}
	}
	return nil
}
