package application

import (
	"fmt"

	"github.com/felixgeelhaar/roady/internal/domain"
	"github.com/felixgeelhaar/roady/internal/domain/planning"
	"github.com/felixgeelhaar/roady/internal/domain/spec"
)

type InitService struct {
	repo  domain.WorkspaceRepository
	audit *AuditService
}

func NewInitService(repo domain.WorkspaceRepository, audit *AuditService) *InitService {
	return &InitService{repo: repo, audit: audit}
}

func (s *InitService) InitializeProject(name string) error {
	if s.repo.IsInitialized() {
		return fmt.Errorf("project already initialized")
	}

	if err := s.repo.Initialize(); err != nil {
		return err
	}
	
	if err := s.audit.Log("project.initialized", "cli", map[string]interface{}{
		"project_name": name,
	}); err != nil {
		// Log but don't fail init? Or fail? TDD says audit is critical.
		return fmt.Errorf("failed to write audit log: %w", err)
	}

	// Create a default skeleton spec
	defaultSpec := &spec.ProductSpec{
		ID:          name,
		Title:       name,
		Description: "Initial product specification generated by roady.",
		Version:     "0.1.0",
		Features: []spec.Feature{
			{
				ID:          "core-foundation",
				Title:       "Core Foundation",
				Description: "The essential building blocks of the project.",
			},
		},
	}

	if err := s.repo.SaveSpec(defaultSpec); err != nil {
		return err
	}

	if err := s.repo.SaveSpecLock(defaultSpec); err != nil {
		return err
	}

	// Create a default policy
	defaultPolicy := &domain.PolicyConfig{
		MaxWIP:  3,
		AllowAI: true,
	}
	if err := s.repo.SavePolicy(defaultPolicy); err != nil {
		return err
	}

	// Initialize Execution State
	initialState := planning.NewExecutionState(name)
	if err := s.repo.SaveState(initialState); err != nil {
		return err
	}

	return s.repo.UpdateUsage(domain.UsageStats{})
}
